# Change these first
owner: gewoonyani2 # Your GitHub organization or username, where this repository lives
repo: Coens-Customs # The name of this repository

sites:
  - name: Main Bot
    check: "tcp-ping"
    url: 66.94.113.204
    port: 6191
  - name: Hub Bot
    check: "tcp-ping"
    url: node2.redon.tech
    port: 25507
  - name: WebSite
    check: "tcp-ping"
    url: node2.redon.tech
    port: 25507
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /Coens-Customs
  logoUrl: https://media.discordapp.net/attachments/1229509714178736299/1229830099323457618/0c9e370a4abddc799d33510fa3b4250c.png?ex=66311b88&is=661ea688&hm=7d0f64574ecccf7be585fe64135b6891ede3d7c558f114668279feb266b12a2e&=&format=webp&quality=lossless&width=607&height=607
  name: Coen's Customs Status
  introTitle: "**Coen's Customs** status page for al our services."
  introMessage: De officiele status pagina van Coen's Customs
  theme: ocean
  navbar:
    - title: Status
      href: /Coens-Customs
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  footer: discord link: https://discord.gg/bNbAza7Ffd
